# Generated by Django 5.2.1 on 2025-07-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_backup_creado_por_alter_backup_modelos_incluidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
