# Generated by Django 5.2.1 on 2025-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde', '0006_devolucioncde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucioncde',
            name='motivo',
            field=models.CharField(max_length=40),
        ),
    ]
