# Generated by Django 5.2.1 on 2025-07-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0011_devolucioncaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucioncaf',
            name='motivo',
            field=models.CharField(max_length=40),
        ),
    ]
