# Generated by Django 5.2.1 on 2025-07-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0012_alter_devolucioncaf_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
