# Generated by Django 5.2.1 on 2025-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0022_alter_devolucion_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='razon',
            field=models.CharField(max_length=40),
        ),
    ]
