# Generated by Django 5.2.1 on 2025-07-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0023_alter_devolucion_razon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
