# Generated by Django 5.2.1 on 2025-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_customuser_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
